io:
  github:
    paulushcgcj:
      database:
        name: simple
        host: 127.0.0.1:5432
        username: simple
        password: root
      oauth:
        realm: Banter
        server: http://127.0.0.1:8000

spring:
  zipkin:
    baseUrl: http://127.0.0.1:9411/