io:
  github:
    paulushcgcj:
      database:
        name: simple
        host: 127.0.0.1:5432
        username: simple
        password: root
      security:
        saltSecret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
        expiration: 7D

spring:
  zipkin:
    baseUrl: http://127.0.0.1:9411/