io:
  github:
    paulushcgcj:
      database:
        host: 127.0.0.1:5432
        name: simple
        username: user
        password: password
      oauth:
        realm: Banter
        server: http://127.0.0.1:8000

spring:
  zipkin:
    baseUrl: http://127.0.0.1:9411/