name: Test
on: [push, pull_request]
jobs:
  release:
    name: Release Test
    runs-on: ubuntu-latest
#    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ github.token }}
          output-file: 'CHANGELOG.md'
          skip-version-file: 'true'
          skip-commit: 'true'

      - name: Check file
        run: cat ./CHANGELOG.md