name: Test
on: [push, pull_request]
jobs:
  release:
    name: Release Test
    runs-on: ubuntu-latest
#    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-maven-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-test-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=version::${VERSION/-SNAPSHOT/}"
          echo "version: ${VERSION/-SNAPSHOT/}" > ./version.yml
        id: get_version

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ github.token }}
          output-file: 'CHANGELOG.md'
          skip-commit: 'true'
          git-push: 'false'
          version-file: './version.yml'
          version-path: 'version'

      - name: Check file
        run: cat ./CHANGELOG.md

      - name: Set new version
        run: mvn versions:set -DnewVersion='${{ steps.changelog.outputs.version }}' -f pom.xml -DskipTests -Dtests.skip=true -Dskip.unit.tests=true

      - name: Update POM
        run: mvn versions:commit

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            pom.xml
            CHANGELOG.md
          commit-msg: "doc: updating pom to ${{ steps.changelog.outputs.version }} [skip ci]"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}