name: Test
on: [push, pull_request]
jobs:
  release:
    name: Release Test
    runs-on: ubuntu-latest
#    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-maven-test-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-test-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Change my log
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          token: ${{ github.token }}

      - name: Update CHANGELOG
        continue-on-error: true
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}


      - name: Changelog
        uses: yashanand1910/standard-release-notes@v1.2.1
        continue-on-error: true
        id: get_release_notes
        with:
          changelog_path: ./CHANGELOG.md # Optional
          version: ${{ github.ref }} # Required

      - name: Check file
        run: cat ./CHANGELOG.md